
    create table alimentazione (
        id_alimentazione integer generated by default as identity,
        tipo_alimentazione varchar(255) not null,
        primary key (id_alimentazione)
    );

    create table bici (
        id_bici integer generated by default as identity,
        id_sospensione integer,
        id_veicolo integer,
        numero_marce integer,
        pieghevole boolean,
        primary key (id_bici)
    );

    create table categoria (
        id_categoria integer generated by default as identity,
        categoria varchar(255),
        primary key (id_categoria)
    );

    create table colore (
        id_colore integer generated by default as identity,
        colore varchar(255),
        primary key (id_colore)
    );

    create table macchina (
        cc integer,
        id_macchina integer generated by default as identity,
        id_veicolo integer,
        numero_porte integer,
        targa varchar(255),
        primary key (id_macchina)
    );

    create table marca (
        id_marca integer generated by default as identity,
        marca varchar(255),
        primary key (id_marca)
    );

    create table modello (
        id_modello integer generated by default as identity,
        modello varchar(255),
        primary key (id_modello)
    );

    create table moto (
        cc integer,
        id_moto integer generated by default as identity,
        id_veicolo integer,
        targa varchar(255),
        primary key (id_moto)
    );

    create table numero_ruote (
        id_numero_ruote integer generated by default as identity,
        numero_ruote integer,
        primary key (id_numero_ruote)
    );

    create table sospensione (
        id_sospensione integer generated by default as identity,
        tipo_sospensione varchar(255),
        primary key (id_sospensione)
    );

    create table veicolo (
        anno_produzione integer,
        id_alimentazione integer,
        id_categoria integer,
        id_colore integer,
        id_marca integer,
        id_modello integer,
        id_numero_ruote integer,
        id_sospensione integer,
        id_veicolo integer generated by default as identity,
        primary key (id_veicolo)
    );

    alter table if exists bici 
       add constraint FK20w9irhi2ejvwwsnhd7mj8pwl 
       foreign key (id_sospensione) 
       references sospensione;

    alter table if exists bici 
       add constraint FKswktcdeh5uuwbhf8ducphchxo 
       foreign key (id_veicolo) 
       references veicolo;

    alter table if exists macchina 
       add constraint FKktm44xfs8hvv5evg3gdfq50u3 
       foreign key (id_veicolo) 
       references veicolo;

    alter table if exists moto 
       add constraint FK45syifcllae09quumt3uhcckk 
       foreign key (id_veicolo) 
       references veicolo;

    alter table if exists veicolo 
       add constraint FKmulkx4clibsa9a7v0hkv33yq2 
       foreign key (id_alimentazione) 
       references alimentazione;

    alter table if exists veicolo 
       add constraint FKadjynej4kplqqaia8h3t3w5m7 
       foreign key (id_categoria) 
       references categoria;

    alter table if exists veicolo 
       add constraint FK1c8wuj83gmqgnjcyerakq2vge 
       foreign key (id_colore) 
       references colore;

    alter table if exists veicolo 
       add constraint FKl2uxral8sefwlju24c4sx1fmw 
       foreign key (id_marca) 
       references marca;

    alter table if exists veicolo 
       add constraint FKgt1s9dk9ulb7f5ml03uxwwici 
       foreign key (id_modello) 
       references modello;

    alter table if exists veicolo 
       add constraint FKlmk3fxo6sm2dnkn96j1ye5ieg 
       foreign key (id_numero_ruote) 
       references numero_ruote;

    alter table if exists veicolo 
       add constraint FKcb3xjc07khmrgstx0cx2ll908 
       foreign key (id_sospensione) 
       references sospensione;
