
    create table abbonamento_attivita (
        abbonamento_id integer not null,
        attivita_id integer not null
    );

    create table abbonamento_socio (
        data_iscrizione date not null,
        id integer generated by default as identity,
        id_socio integer,
        primary key (id)
    );

    create table attivita (
        id integer generated by default as identity,
        prezzo numeric(38,2),
        descrizione_attivita varchar(100) not null,
        primary key (id)
    );

    create table certificato_medico (
        data_certificato date,
        id integer generated by default as identity,
        socio_id integer unique,
        tipo_certificato boolean,
        primary key (id)
    );

    create table messaggi_sistema (
        code varchar(255) not null,
        lang varchar(255) not null,
        messaggio varchar(255),
        primary key (code, lang)
    );

    create table socio (
        id integer generated by default as identity,
        codice_fiscale varchar(16) not null unique,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        email varchar(255),
        primary key (id)
    );

    alter table if exists abbonamento_attivita 
       add constraint FK853iwjge5sco7nac3v8pvs72v 
       foreign key (attivita_id) 
       references attivita;

    alter table if exists abbonamento_attivita 
       add constraint FK7slwjgyb7wchv5gnm07g9m6v1 
       foreign key (abbonamento_id) 
       references abbonamento_socio;

    alter table if exists abbonamento_socio 
       add constraint FKnocg3o0qcq1tningp2l4lmk6r 
       foreign key (id_socio) 
       references socio;

    alter table if exists certificato_medico 
       add constraint FKr17u6bpruq0epjt5g760mbe7c 
       foreign key (socio_id) 
       references socio;
